//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace customFonts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class customFonts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal customFonts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("customFonts.Resources.customFonts", typeof(customFonts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log off and log back on to apply the patch. Do you want to log off now?.
        /// </summary>
        internal static string confLogoff1 {
            get {
                return ResourceManager.GetString("confLogoff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log off so customFonts can apply the patch?.
        /// </summary>
        internal static string confLogoff2 {
            get {
                return ResourceManager.GetString("confLogoff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customFonts requires at least logging off and logging back on to patch the font. Do you want to log off now?.
        /// </summary>
        internal static string confLogoff3 {
            get {
                return ResourceManager.GetString("confLogoff3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem while patching {0}. We reverted the changes so you should not see any font problems..
        /// </summary>
        internal static string problem1 {
            get {
                return ResourceManager.GetString("problem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an problem while patching {0}, and we reverted the changes..
        /// </summary>
        internal static string problem2 {
            get {
                return ResourceManager.GetString("problem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadly,.
        /// </summary>
        internal static string probString1 {
            get {
                return ResourceManager.GetString("probString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an problem, so....
        /// </summary>
        internal static string probString2 {
            get {
                return ResourceManager.GetString("probString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string probString3 {
            get {
                return ResourceManager.GetString("probString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching {0} requires Windows 11 or later..
        /// </summary>
        internal static string requires220001 {
            get {
                return ResourceManager.GetString("requires220001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching {0} requires 10.0.22000.x or later..
        /// </summary>
        internal static string requires220002 {
            get {
                return ResourceManager.GetString("requires220002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching {0} only works on Windows 11 or later..
        /// </summary>
        internal static string requires220003 {
            get {
                return ResourceManager.GetString("requires220003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold up!.
        /// </summary>
        internal static string waitString1 {
            get {
                return ResourceManager.GetString("waitString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait!.
        /// </summary>
        internal static string waitString2 {
            get {
                return ResourceManager.GetString("waitString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string waitString3 {
            get {
                return ResourceManager.GetString("waitString3", resourceCulture);
            }
        }
    }
}
